### ISSUE TITLE
osx 10.14.6 打不开

### ISSUE THREAD

**Issue by cryzlasm** [Skyminers/smartQR-public#1]
![image](https://user-images.githubusercontent.com/20424580/164212694-aa4a33f6-5210-48e9-8c1a-82444c3ef100.png)

**Comment by Skyminers** [comment]
软件的系统版本要求确实过高，目前在最新的 Release 中降低了对系统版本的要求。
但是由于使用了一些 macOS 11.0 的窗口机制，目前还是要求 macOS 11.0 或更高版本，非常抱歉。
